"use strict";

(function exposePocketPotionRelationshipContent(root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  if (root) root.PPWRelationshipContent = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function createPocketPotionRelationshipContent() {
  function deepFreeze(value) {
    if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
    for (const nested of Object.values(value)) deepFreeze(nested);
    return Object.freeze(value);
  }

  const DELIVERY_NARRATIVE_PILOTS = [
    { customerId: "customer-0", fromHearts: 0, toHearts: 1, kicker: "MIRA · FIRST TRUST HEART", title: "The early list", body: "Before sunrise, Mira is checking the small slate where she records which opening trays sell first and which need another try. A flour tin is holding down one corner because the bakery door keeps letting in a sharp draft. You slide a folded cloth beneath the slate so it stays level, then hold the door while she writes down the two trays already cooling. \"There,\" she says. \"Now I can tell what actually worked.\" When the first loaves come out even, Mira laughs with relief and leaves one blank line for the next tray worth testing.", footer: "1 of 3 trust hearts · Mira keeps her opening-tray slate by the oven, with one blank test line." },
    { customerId: "customer-0", fromHearts: 1, toHearts: 2, kicker: "MIRA · SECOND TRUST HEART", title: "A taste before opening", body: "Four market mornings later, Mira brings a covered basket to the workshop before the shutters lift. Inside are three little oat loaves, each wrapped in parchment and tied with a different-colored string. You cut them into equal pieces with the butter knife she packed, then point to the apple loaf after its warm scent fills the doorway. Mira tastes it, looks at the empty crumbs on that plate, and writes RED STRING on her slate before circling those words. \"That one is plainly the favorite,\" she says. \"Thank you for helping me choose.\" She leaves the basket at your counter for the morning customers.", footer: "2 of 3 trust hearts · Mira records the red-string apple loaf as her next opening batch." },
    { customerId: "customer-0", fromHearts: 2, toHearts: 3, kicker: "MIRA · THIRD TRUST HEART", title: "The last warm slice", body: "A week later, Mira arrives at dusk with the same slate tucked under her arm. The red-string apple loaf sold out before noon, and she has brought one last warm slice for you to taste. You tap the cinnamon jar beside the cauldron. Mira opens it and smells the cinnamon, then writes \"one pinch cinnamon\" beside the RED STRING note on her slate. She takes the note back to the bakery and tests the change in the next opening batch. The following morning, she returns with an empty basket and a pleased nod. She adds one clear line to the slate: \"one workshop slice with every opening batch.\"", footer: "3 of 3 trust hearts · Mira now adds a workshop slice to every opening batch." },
    { customerId: "customer-1", fromHearts: 0, toHearts: 1, kicker: "OLD MOSS · FIRST TRUST HEART", title: "The little chime", body: "After a hard shower, Old Moss stops outside the workshop with a damp coat, a tin cup, and two little acorn chimes threaded on waxed string. He says the lane by the hedges is \"thinking about becoming a pond.\" He has already walked the raised route behind the elm and knows it is clear. You hold the shop lantern while he ties one chime at the elm turn. \"It will help people find this turn when rain hides the path,\" he explains. Before leaving, he hangs the other, the spare, by the workshop door so anyone caught in bad weather knows where to meet.", footer: "1 of 3 trust hearts · The route chime marks the elm turn; the spare marks the workshop meeting door." },
    { customerId: "customer-1", fromHearts: 1, toHearts: 2, kicker: "OLD MOSS · SECOND TRUST HEART", title: "A fidgety branch", body: "Two rainy days later, the spare chime knocks gently against the workshop door. Old Moss is already outside, looking pleased and mildly offended. The elm's low branch has rubbed the route chime against a knot, leaving its string frayed. You bring fresh waxed string and hold the lantern while he moves the chime one hand higher on the branch. \"Branches are fidgety neighbors,\" he explains. Then you stand together at the workshop door and listen through the rain. From there, you can hear the route chime, while the spare still marks the place where walkers should gather first.", footer: "2 of 3 trust hearts · The repaired route chime can be heard from the workshop meeting door." },
    { customerId: "customer-1", fromHearts: 2, toHearts: 3, kicker: "OLD MOSS · THIRD TRUST HEART", title: "The dry way home", body: "The following week, rain catches the evening market just as the bakers begin packing up. Neighbors spot the spare acorn chime at the workshop door and gather beneath its awning while Old Moss brings an armful of umbrellas for everyone. You help keep the group together as he leads everyone to the elm. The repaired route chime rattles at the turn, so no one misses the raised path behind it. The neighbors follow with their shoes mostly clean. At the far gate, Moss says, \"Reliable enough for company.\" When the rain eases, the spare chime is still hanging by the workshop door.", footer: "3 of 3 trust hearts · The workshop meeting chime and elm route marker guide neighbors to the raised path." },
    { customerId: "customer-2", fromHearts: 0, toHearts: 1, kicker: "JUNIPER · FIRST TRUST HEART", title: "The missing page", body: "Behind the mill, Juniper's music pages keep lifting from their stand whenever the wheel catches a breeze. One sheet skids across the grass, and you catch it before it reaches the water. Juniper groans, then laughs. \"A dramatic exit for a very shy note.\" You fasten the pages with the plain brass clip from a supply box, and she tries the troublesome passage again. This time she makes it to the end without chasing paper. She writes a small dot beside the bar where she usually stops and folds the clipped pages carefully into her case.", footer: "1 of 3 trust hearts · A brass clip holds Juniper's pages, and one difficult bar is marked." },
    { customerId: "customer-2", fromHearts: 1, toHearts: 2, kicker: "JUNIPER · SECOND TRUST HEART", title: "One more run-through", body: "The next Friday, Juniper has set two stools behind the mill: one for her case and one facing the water. She says the marked bar still feels like a loose floorboard. You take the spare stool and turn pages when she nods. The first attempt wobbles, so she stops, makes a face, and starts again before you can politely look away. On the second pass, the brass clip flashes in the sun and she clears the bar cleanly. Juniper adds a penciled pause before it. \"That is where I remember to breathe,\" she says.", footer: "2 of 3 trust hearts · The marked bar gains a breathing pause, and the second stool stays by the mill." },
    { customerId: "customer-2", fromHearts: 2, toHearts: 3, kicker: "JUNIPER · THIRD TRUST HEART", title: "The open rehearsal", body: "Several weeks later, a delivery cart breaks a wheel in the market square, and people gather under the awning. Juniper carries her case from the mill and sets it on its usual stool. You sit on the second stool beside a dry fruit crate, the only dry surface available for her score. Juniper sets the score on the crate; you fasten it with the brass clip and turn its pages while she plays. When a few neighbors turn to listen, Juniper pauses, then says she will finish this one. She clears the marked passage, takes the penciled breathing pause, and plays on. Afterward, both stools return to the mill.", footer: "3 of 3 trust hearts · Juniper returns both stools to the mill and keeps the listener's stool ready." },
    { customerId: "customer-6", fromHearts: 0, toHearts: 1, kicker: "FERN · FIRST TRUST HEART", title: "The seed that would not wake", body: "Fern sets a blue clay pot on the counter. Its soil is dark and carefully tended, but bare. \"I've tried sun, shade, songs, and apologizing to it,\" she says. \"I keep telling everyone it just needs more time, but I'm starting to think I'm wrong.\" She asks if she can leave the pot beside your warm cauldron for a few days, and you clear it a place.", footer: "1 of 3 trust hearts · The blue pot stays in your workshop" },
    { customerId: "customer-6", fromHearts: 1, toHearts: 2, kicker: "FERN · SECOND TRUST HEART", title: "What help looks like", body: "A few days later, Fern returns to check the blue pot and finds a tiny green shoot breaking through the soil. It has grown toward the cauldron and is beginning to lean. Fern reaches to move it closer to the warmth, but you point to the morning light at the nearby window. Together you move the pot where it can have both, then brace the stem with a folded order slip. \"I thought being patient meant leaving it alone,\" Fern says. \"But sometimes patience means watching closely and helping at the right time.\"", footer: "2 of 3 trust hearts · The seedling moves to the workshop window" },
    { customerId: "customer-6", fromHearts: 2, toHearts: 3, kicker: "FERN · THIRD TRUST HEART", title: "A place by the window", body: "Some time later, Fern visits the workshop again and takes one look at the blue pot. A small violet flower has opened above the leaves. \"It bloomed!\" she says, then laughs when you point to the folded order slip still supporting the stem. Fern brushes a little soil from the sill while you turn the flower toward the light. She adds a painted label: PATIENCE. \"It did most of the work,\" she says. \"But I think it liked having both of us around.\" When Fern reaches to take the pot home, you tap its place by the window. She smiles and leaves it there.", footer: "3 of 3 trust hearts · Patience stays by the workshop window" },
    { customerId: "customer-3", fromHearts: 0, toHearts: 1, kicker: "POSTMASTER PIP · FIRST TRUST HEART", title: "The ribbon at the gate", body: "On a breezy afternoon, Pip skids into the workshop with a small bundle of blank address cards and a blue ribbon caught around his satchel strap. A garden gate on his route has been swinging open, he explains, and every gust sends the cards fluttering into the path. You hold the gate steady while he threads the ribbon through its loose latch, then use the empty cards to test the wind. They stay put. Pip checks the ribbon twice, grins, and tucks the cards back into his satchel. \"A route with fewer flying papers is a very fast route,\" he says.", footer: "1 of 3 trust hearts · The blue ribbon now keeps the garden gate latched and Pip's address cards from blowing into the path." },
    { customerId: "customer-3", fromHearts: 1, toHearts: 2, kicker: "POSTMASTER PIP · SECOND TRUST HEART", title: "The damp corner", body: "Three rainy mornings later, Pip finds you beneath the same garden gate with the blue ribbon still holding firm. One address card has a damp corner from a puddle near the hedge. You spread it on the workshop counter and press it flat under a clean jar while Pip sketches the gate and puddle in the margin of a fresh card. Together you carry a flat stepping stone from the garden border to the wet spot. Pip hops across it, then crosses again at his usual hurry. \"Officially a better crossing,\" he declares, and adds a tiny stone symbol to his route note.", footer: "2 of 3 trust hearts · A stepping stone protects the gate crossing; Pip's route note now marks it." },
    { customerId: "customer-3", fromHearts: 2, toHearts: 3, kicker: "POSTMASTER PIP · THIRD TRUST HEART", title: "The dry delivery", body: "The next week brings a proper downpour just as Pip reaches the workshop with a sealed letter for the gardener beyond the hedge. He pauses at the blue-ribbon gate, spots the stepping stone, and hands you the satchel while he closes his umbrella. You cross first, keeping the letter high and dry; Pip follows, laughing when the stone saves his polished shoes from the puddle. At the far gate, he takes back the satchel and delivers the letter without a wrinkled corner. On his return, Pip adds one neat note beside the stone symbol: \"trusted in rain.\"", footer: "3 of 3 trust hearts · Pip keeps the blue-ribbon gate and marked stepping stone on his rainy-day route." },
    { customerId: "customer-4", fromHearts: 0, toHearts: 1, kicker: "LADY BRAMBLE · FIRST TRUST HEART", title: "The small brass key", body: "Lady Bramble arrives with a tiny brass key tied to a green thread and asks you to look at its stubborn little bow. It belongs to a wooden seed chest in her back hall, she says, and the thread keeps catching whenever she opens it. You set the key on a cloth, smooth the knot, and loop the thread through a buttonhole-sized ring from a spare tag. Bramble tries the chest key again, then gives the ring an approving tap. \"Orderly, but not so orderly that it stops being charming,\" she says. She leaves the key on the workshop shelf until morning so the new loop can settle.", footer: "1 of 3 trust hearts · The brass key has a loose green-thread loop and waits on the workshop shelf overnight." },
    { customerId: "customer-4", fromHearts: 1, toHearts: 2, kicker: "LADY BRAMBLE · SECOND TRUST HEART", title: "The labeled drawers", body: "The following day, Lady Bramble returns for the key carrying three seed packets with their names rubbed away. You fetch the seed chest from her back hall and spread the packets beside it on the workshop table. She remembers one packet smelled peppery and another made a very poor hiding place for a snail. You sort the remaining clues into little paper sleeves; she writes simple labels in her tidy hand. The brass key opens the chest without catching, and Bramble slips the sleeves into its top drawer. \"You have made my disorder quite presentable,\" she says.", footer: "2 of 3 trust hearts · The seed chest now holds three labeled sleeves, opened by the green-looped brass key." },
    { customerId: "customer-4", fromHearts: 2, toHearts: 3, kicker: "LADY BRAMBLE · THIRD TRUST HEART", title: "The right drawer", body: "A few days later, Bramble finds a fourth unmarked packet on her doorstep after a night of strong wind. She brings it straight to the workshop instead of guessing. You compare its leaf shape to the sketches on the three paper sleeves, and she notices it matches the peppery packet's curled edge. Together you label it before it can disappear into a drawer. Back at the seed chest, the green-looped key turns easily and Bramble files the new sleeve beside its match. She pauses before closing the lid. \"Next time, we begin with the drawer,\" she says, pleased.", footer: "3 of 3 trust hearts · Lady Bramble uses the labeled seed chest as a shared starting place for new garden mysteries." },
    { customerId: "customer-5", fromHearts: 0, toHearts: 1, kicker: "TINK THE SMITH · FIRST TRUST HEART", title: "The rolling washer", body: "Tink spots a small iron washer rolling under your worktable and drops to one knee before it can vanish behind the flour tins. He says it slipped from a hand-cranked label press he is making for workshop jars. You slide a shallow tray under the table while he nudges the washer into it with a spoon. At the forge, he fits it back onto the press and turns the handle. The label comes out crooked but readable: MINT, almost. Tink squints, then lets you add a pencil arrow showing which way the washer should face next time.", footer: "1 of 3 trust hearts · The washer sits correctly in Tink's label press, with a pencil arrow for its proper direction." },
    { customerId: "customer-5", fromHearts: 1, toHearts: 2, kicker: "TINK THE SMITH · SECOND TRUST HEART", title: "A steadier turn", body: "Two market days later, Tink brings the label press to the workshop with the washer still in place but the pencil arrow smudged from use. You hold the press steady while he turns its handle slowly, and the first label reads MINT without leaning. The second jams halfway through. Instead of yanking it free, Tink sets the press on the tray you used under the table and you both lift the paper back in one piece. He redraws the arrow on a small metal tab and ties the tab to the handle with twine. \"That should survive my enthusiasm,\" he says.", footer: "2 of 3 trust hearts · A metal direction tab now hangs from the press handle; the tray catches any jammed labels." },
    { customerId: "customer-5", fromHearts: 2, toHearts: 3, kicker: "TINK THE SMITH · THIRD TRUST HEART", title: "Labels before lunch", body: "The next Saturday, jars have gathered on your counter before the morning rush. Tink sets his press beside the shallow tray, checks the metal tab, and hands you the blank labels one at a time. You line up each jar while he gives the handle its steady turn. When one label starts to crease, you catch it in the tray and Tink resets the paper without fuss. Soon every jar has a straight name, including the smallest amber bottle. Tink reads that last label aloud, nods solemnly, and leaves the press by your counter for the afternoon.", footer: "3 of 3 trust hearts · Tink's label press, direction tab, and shallow tray make a reliable workshop counter routine." },
  ];

  return deepFreeze({ DELIVERY_NARRATIVE_PILOTS });
});
