const fs = require("fs");
const vm = require("vm");

const files = ["index.html", "style.css", "content-data.js", "game-logic.js", "platform-adapters.js", "audio-feedback.js", "app.js", "serve.cjs", "manifest.webmanifest", "service-worker.js", "icon.svg", "ASSET_PROVENANCE.md"];
const missing = files.filter(file => !fs.existsSync(file));
if (missing.length) throw new Error(`Missing files: ${missing.join(", ")}`);

const combined = files.map(file => fs.readFileSync(file, "utf8")).join("\n");
if (!combined.includes("Pocket Potion Works") || !combined.includes("pocket-potion-works")) {
  throw new Error("Product identity is incomplete across the required files.");
}

const html = fs.readFileSync("index.html", "utf8");
const normalizedHtml = html.replace(/\r\n/g, "\n");
const content = fs.readFileSync("content-data.js", "utf8");
const app = fs.readFileSync("app.js", "utf8");
const style = fs.readFileSync("style.css", "utf8");
if (!app.includes("already been added to the Pantry")) throw new Error("Welcome Back must state that offline ingredients were already added to the Pantry.");
if (!app.includes('label: "Back to workshop", primary: true')) throw new Error("Welcome Back must use a non-claiming return action.");
if (app.includes('label: "Collect ingredients"')) throw new Error("Welcome Back must not offer a second ingredient collection step.");
if (!html.includes('<script src="content-data.js"></script>')) throw new Error("Content data must load before pure game logic.");
if (!html.includes('<script src="game-logic.js"></script>')) throw new Error("Pure game logic must load before the browser adapter.");
if (!html.includes('<script src="platform-adapters.js"></script>')) throw new Error("Platform adapters must load before the browser adapter.");
if (!html.includes('<script src="audio-feedback.js"></script>')) throw new Error("Audio helpers must load before the browser adapter.");
if (!normalizedHtml.includes('content-data.js"></script>\n    <script src="game-logic.js"></script>\n    <script src="platform-adapters.js"></script>\n    <script src="audio-feedback.js"></script>\n    <script src="app.js')) throw new Error("Browser scripts must load in dependency order.");
const ids = new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]));
const queriedIds = [...app.matchAll(/querySelector\(["'`]#([A-Za-z0-9_-]+)["'`]\)/g)].map(match => match[1]);
const dynamicIds = new Set(["collectBrewButton"]);
const absentIds = [...new Set(queriedIds.filter(id => !ids.has(id) && !dynamicIds.has(id)))];
if (absentIds.length) throw new Error(`JavaScript references absent HTML IDs: ${absentIds.join(", ")}`);
if (!html.includes('id="brewStatusAnnouncement" role="status" aria-live="polite" aria-atomic="true"')) throw new Error("Brew transitions require one stable atomic live status node.");
for (const id of ["workshopNarrativeDelivery", "ordersNarrativeDelivery"]) if (!html.includes(`id="${id}" role="status" aria-live="polite" aria-atomic="true"`)) throw new Error("Narrative delivery surfaces require stable atomic live status nodes.");
if (!html.includes('id="reservedStoryKicker"') || !app.includes("Logic.reservedStoryTracker(state)")) throw new Error("The reserved-story tracker must support After the Stars and The Village Loaf through one surface.");
if (!app.includes("Village Chapter") || !fs.readFileSync("style.css", "utf8").includes('data-cosmetic="firstlight"')) throw new Error("The Village Loaf ribbon and Firstlight Bakery look must remain wired.");
if (!app.includes('fulfillOrder(Number(button.dataset.quickDeliver), "workshop")') || !app.includes('fulfillOrder(Number(button.dataset.order), "orders")')) throw new Error("Narrative delivery must retain its originating surface.");
if (!app.includes('Logic.orderAction(state, order)') || !app.includes('data-next') || !app.includes('function routeOrderAction(orderId)')) throw new Error("Ordinary not-ready orders must use the state-aware navigation route.");
if (!app.includes('function focusTarget(target)') || !app.includes('setDisclosure("recipes", true)')) throw new Error("Ordinary order guidance must retain Workshop target focus.");
const miraRuntime = "assets/images/villagers/mira-head.png";
const miraSource = "assets/source/villagers/mira_head-256.png";
const avatarHelperStart = app.indexOf("const MIRA_PORTRAIT_MARKUP");
const avatarHelperEnd = app.indexOf("const $ =", avatarHelperStart);
const avatarHelper = app.slice(avatarHelperStart, avatarHelperEnd);
if (avatarHelperStart < 0 || (style.match(new RegExp(miraRuntime, "g")) || []).length !== 1 || !avatarHelper.includes('customerId === "customer-0"') || !avatarHelper.includes(": avatar")) throw new Error("Mira must use one portrait seam while other villagers keep their emoji fallback avatars.");
const ordersPath = app.slice(app.indexOf("function renderOrders()"), app.indexOf("function focusTarget"));
const requestsPath = app.slice(app.indexOf("function showSpecialRequestChooser"), app.indexOf("function renderWeekly"));
const journalPath = app.slice(app.indexOf("function renderJournal()"), app.indexOf("function claimJournalEntry"));
if (!ordersPath.includes("customerAvatarMarkup(order.customerId, order.avatar, order.avatarColor)") || !requestsPath.includes("customerAvatarMarkup(commission.customerId, customer[1], customer[3])") || !journalPath.includes("customerAvatarMarkup(customerId, customer[1], customer[3])")) throw new Error("Mira portrait must use the shared avatar seam on order, request, and Journal surfaces.");
const chapterPayoffStart = app.indexOf("function showChapterPayoff(result, surface)");
const chapterPayoffEnd = app.indexOf("function openModal(", chapterPayoffStart);
const chapterPayoffPath = app.slice(chapterPayoffStart, chapterPayoffEnd);
if ((content.match(/payoff: Object\.freeze\(/g) || []).length !== 3 || chapterPayoffStart < 0 || chapterPayoffEnd < 0 || !app.includes("if (result.chapter) showChapterPayoff(result, surface);")) throw new Error("All three authored chapter payoffs must use the surface-aware modal acknowledgement path.");
for (const field of ["kicker", "title", "body", "footer"]) if (!chapterPayoffPath.includes(`result.narrative.${field}`)) throw new Error(`Chapter payoff modal must present its authored ${field}.`);
if (chapterPayoffPath.includes("setTimeout") || chapterPayoffPath.includes("beginCompletionState")) throw new Error("Chapter payoff acknowledgement must not auto-dismiss.");
if (!app.includes('if (result.narrative && !result.chapter) beginCompletionState(surface === "workshop" ? "narrativeWorkshop" : "narrativeOrders", result.narrative);')) throw new Error("Non-chapter narrative behavior must retain its originating passive surface.");
const chapterClose = chapterPayoffPath.indexOf("closeModal();");
const chapterOrdersView = chapterPayoffPath.indexOf('switchView("orders")');
const chapterTarget = chapterPayoffPath.indexOf(".order-card.is-chapter");
if (!app.includes('if (result.chapter) showChapterPayoff(result, surface);\n  else if (restoreReservedFocus)') || !chapterPayoffPath.includes('"Continue the chapter"') || !(chapterClose < chapterOrdersView && chapterOrdersView < chapterTarget)) throw new Error("Continue must close the modal, open Orders, then focus the next chapter target.");
if (!chapterPayoffPath.includes("lastFocus = $(surface === \"orders\" ? \"#ordersView h1\" : '[data-nav=\"workshop\"]');") || !chapterPayoffPath.includes('if (surface === "orders") lastFocus.tabIndex = -1;')) throw new Error("Chapter dismissal must return to the Orders heading or a visible Workshop control.");
if (!chapterPayoffPath.includes('"View Workshop Looks"') || !chapterPayoffPath.includes('switchView("journal")') || !chapterPayoffPath.includes('button[data-cosmetic="firstlight"]') || !app.includes('focusTarget($(`button[data-cosmetic="${cosmeticId}"]`));')) throw new Error("The final chapter action and Workshop Look selections must retain focus on Firstlight Bakery.");
if (!chapterPayoffPath.includes("icon: MIRA_PORTRAIT_MARKUP")) throw new Error("Every Village Chapter payoff must use the shared Mira portrait.");
const modalPath = app.slice(app.indexOf("function openModal({"), app.indexOf("function closeModal()"));
if (!modalPath.includes("modalIcon.innerHTML = icon;") || !modalPath.includes('modalIcon.classList.toggle("is-mira-portrait", icon === MIRA_PORTRAIT_MARKUP);')) throw new Error("Opening any non-Mira modal must clear Mira portrait state.");
const worker = fs.readFileSync("service-worker.js", "utf8");
const budgets = JSON.parse(fs.readFileSync("release-budgets.json", "utf8"));
const workflow = fs.readFileSync(".github/workflows/pages.yml", "utf8");
if (!fs.existsSync(miraSource) || fs.existsSync("assets/images/villagers/mira_head.png") || !worker.includes(`./${miraRuntime}`) || worker.includes(miraSource) || workflow.includes("assets/source") || budgets.files[miraRuntime] !== 24000 || Object.hasOwn(budgets.files, miraSource)) throw new Error("Mira runtime portrait must be budgeted, cached, and deployed without shipping source artwork.");
if (app.includes('class="active-brew" aria-live=')) throw new Error("The per-second brew countdown must remain outside live regions.");

JSON.parse(fs.readFileSync("manifest.webmanifest", "utf8"));
new vm.Script(content, { filename: "content-data.js" });
new vm.Script(app, { filename: "app.js" });
console.log(`Verification passed: ${files.length} required files, ${ids.size} UI IDs, product identity and syntax checks passed.`);
